controller_list:
  - name: fake_arm_controller
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
  - name: fake_end_effector_controller
    joints:
      []
initial:  # Define initial robot poses.
  - group: arm
    pose: rest